# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Installing Modules in /frontend'
  inputs:
    command: 'install'
    workingDir: 'frontend'

- task: Npm@2
  displayName: 'Installing Modules in /backend'
  inputs:
    command: 'install'
    workingDir: 'backend'

- task: Npm@3
  displayName: 'Building Modules in /frontend'
  inputs:
    command: 'custom'
    workingDir: 'frontend'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    Contents: |
      client/dist/**
      server/**
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'